/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package post;

import Model.Invoice;
import Model.SaledItem;
import java.io.IOException;
import java.util.Date;

/**
 * Class for sales log generated by the POST.
 * Class can add and print sales log using sales from the POST.
 */
public class SalesLog {
    
	/**
	 * Adds a new sale to the sales log.
	 * @param sale Sale object containing details of sale to add to sales log
	 * @param store Store in which POST is utilized
	 * @throws IOException
	 */
    public void addNewSale(Sale sale, Store store) throws IOException{
        Invoice invoice = new Invoice(sale.getCustName(), sale.getSaledItems(), sale.getSaledtime(), 
                sale.getPayment().isCash(), sale.getPayment().amount(), sale.getPayment().cashReceived(), 
                sale.getPayment().cashReturned(), sale.getPayment().cardNo());
        invoice.run();//write transaction.txt
        
        /*Display Invoice*/
        System.out.println("----Invoice Printed by Program------");
        System.out.println(store.getSname().toUpperCase());// display store name
        System.out.println("Customer name: "+sale.getCustName()+", Date Time: "+ sale.getSaledtime());
        for(SaledItem item:sale.getSaledItems()){
            double subtotal = item.getQuantity()*item.getItem().getPrice();
            System.out.println("ITEM: <"+item.getItem().getDescription()+" "+item.getQuantity()+
                    " @ "+item.getItem().getPrice()+" "+subtotal+">");
        }
        System.out.println("----");
        System.out.println("Total $"+sale.getPayment().amount());
        if(sale.getPayment().isCash()){
            System.out.println("Amount Tendered: "+sale.getPayment().cashReceived());
            System.out.println("Amount Returned: "+sale.getPayment().cashReturned());
        }else{
            System.out.println("Paid by Credit Card "+sale.getPayment().cardNo());
        }
    }
    
    /**
     * Prints sales log for a given date. (Not currently implemented)
     * @param time Date of sales to be printed
     */
    public void printSalesLog(Date time){
        
    }
    
    /**
     * Prints sales record for a given customer. (Not currently implemented)
     * @param Custname Name of customer of whom to print sales.
     */
    public void printRecord(String Custname){
        
    }
}
